name: Lint Build Deployment Task
on:
  push:
    branches:
      - master
env:
  GREETING: Hello
  USER: ${{secrets.USER}}
  PASSWORD: ${{secrets.PASSWORD}}
jobs:
  test:
    environment: dev
    env:
      NAME: Seetal Ranjan Sahoo
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Node js
        uses: actions/setup-node@v4
      - name: Cache Dependencies
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: deps-mode-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install Dependancies
        run: npm ci
      - name: run lint
        run: npm run lint
      - name: test
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file : ${{steps.publish.outputs.script-file1}}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Node js
        uses: actions/setup-node@v4
      - name: Cache Dependencies
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: deps-mode-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install Dependancies
        run: npm ci
      - name: run build
        run: npm run build
      - name: Publish js filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file1={}'>> $GITHUB_OUTPUT ';'
      - name: Upload atrifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Atrifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output content
        run: ls
      - name: Output file name
        run: echo "${{needs.build.outputs.script-file}}"
      - name: deployment
        run: | 
          echo "DEPLOY TASK RUNNING..."
          echo "Global Environment value $GREETING"
          echo "Local Environment value ${{env.NAME}}"
          echo "Username ${{env.USER}}"
          echo "password ${{env.PASSWORD}}"
